---

version: "v-{build}"

image: Visual Studio 2022

clone_folder: C:\projects\clj-kondo

environment:
  GRAALVM_HOME: C:\projects\babashka\graalvm\graalvm-jdk-23+37.1
  JAVA_HOME: C:\projects\babashka\graalvm\graalvm-jdk-23+37.1

cache:
  - C:\ProgramData\chocolatey\lib -> project.clj, appveyor.yml
  - '%USERPROFILE%\.m2 -> project.clj'
  - 'graalvm -> appveyor.yml'

clone_script:
- ps: >-
    if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
      git clone -q --branch=$env:APPVEYOR_REPO_BRANCH https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
      cd $env:APPVEYOR_BUILD_FOLDER
      git checkout -qf $env:APPVEYOR_REPO_COMMIT
    } else {
      git clone -q https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
      cd $env:APPVEYOR_BUILD_FOLDER
      git fetch -q origin +refs/pull/$env:APPVEYOR_PULL_REQUEST_NUMBER/merge:
      git checkout -qf FETCH_HEAD
    }
#- cmd: git submodule update --init --recursive

build_script:
- cmd: >-

    powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein.bat', 'lein.bat')"

    call lein self-install
    call lein with-profiles +extract-deps deps

    set CLJ_KONDO_TEST_ENV=jvm

    REM call script/test.bat

- cmd: >-
    call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"

    powershell -Command "if (Test-Path('graalvm')) { return } else { (New-Object Net.WebClient).DownloadFile('https://download.oracle.com/graalvm/23/archive/graalvm-jdk-23_windows-x64_bin.zip', 'graalvm.zip') }"

    powershell -Command "if (Test-Path('graalvm')) { return } else { Expand-Archive graalvm.zip graalvm }"

    where java

    java -version

    REM set the PATH only after you ran vcvars64 since it wipes the existing PATH

    set JAVA_HOME=%GRAALVM_HOME%

    set PATH=%GRAALVM_HOME%\bin;%PATH%

    echo %PATH%

    echo %VSINSTALLDIR%

    where cl

    where java

    dir graalvm

    dir %GRAALVM_HOME%\bin

    where native-image

    call script/compile.bat

    echo Creating zip archive

    set /P CLJ_KONDO_VERSION=< resources\CLJ_KONDO_VERSION

    set zip=clj-kondo-%CLJ_KONDO_VERSION%-windows-amd64.zip

    jar -cMf %zip% clj-kondo.exe

    powershell -Command "if (Test-Path('bb.exe')) { return } else { (New-Object Net.WebClient).DownloadFile('https://github.com/borkdude/babashka/releases/download/v0.10.163/babashka-0.10.163-windows-amd64.zip', 'bb.zip') }"

    powershell -Command "if (Test-Path('bb.exe')) { return } else { Expand-Archive bb.zip . }"

    bb release-artifact %zip%

- cmd: >-
    lein clean

    set CLJ_KONDO_TEST_ENV=native

    call script/test.bat

artifacts:
- path: clj-kondo-*-windows-amd64.zip
  name: clj-kondo
