name: Linting diff

on: [push]

jobs:
  linting-diff:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@2.0
      with:
        tools-deps: '1.10.1.469'
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-project-clj-${{ hashFiles('**/project.clj') }}
    - name: Diff
      run: ./script/diff || true
